# -*- coding: utf-8 -*-
"""Public_sentiment_Analysis_BaseballTeams.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v5HvuiHs7eM-Ov7wsbi8Ciat48twDs8M
"""

import requests
from bs4 import BeautifulSoup

url = "https://www.ptt.cc/bbs/Baseball/index.html"

articles = []

for times in range(30):
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'html.parser')
    article = soup.select('.title a')
    
    paging = soup.select('.btn-group.btn-group-paging a')
                           
    last_url = "https://www.ptt.cc" + paging[1]['href']
    
    for each_title in article:
      articles.append(each_title.text)
        #print(each_title.text, "https://www.ptt.cc" + each_title['href'])
    
    url = last_url

len(articles)

import pandas as pd
from matplotlib.font_manager import FontProperties
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei'] #提供字型避免圖軸標題中文產生亂碼
plt.rcParams['axes.unicode_minus'] = False

colrogroup1 = ['#427f8f','#4a8fa1','#559db0','#66a7b8','#77b1c0','#89bbc8','#9ac5d0','#bdd9e0','#cee3e8','#e0edf0']
#藍色漸層
colrogroup2 = ['#cd0003','#e60003','#ff0004','#ff1a1d','#ff3436','#ff4d4f','#ff6768','#ff8181','#ff9a9b','#ffb4b4']
#紅色漸層

#決定所欲查詢比對之聲量標的
teams_name = ['中信','樂天','富邦','味全龍','統一獅'] 

brand_count = []
for name in teams_name:
    count = 0
    for mentioned in articles:
        if name in mentioned:
            count = count + 1
    brand_count.append(count)

print(brand_count)

plt.bar(teams_name, brand_count, color=colrogroup1) 
labels = ['CITIC Brothers','Lotte Peach Ape','Fubon Titans','Weiquanlong','Unity 7-ELEVEn Lion']
plt.xticks(ticks=teams_name,
          labels=labels,fontsize=15,rotation=90) 
#plt.xticks(fontsize=15,rotation=90)
#ax.set_xticklabels(labels = labels)
for index, data in enumerate(brand_count):
    plt.text(x=index, y =data, s=data, verticalalignment="top", horizontalalignment="center")
    
plt.xlabel('Baseball Team', fontsize=15)
plt.ylabel('voice', fontsize=15)
plt.title('Analysis of the voice of Baseball Team', fontsize=20)
plt.show()